# Generated by Django 5.2 on 2026-02-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
